### ISSUE TITLE
Any documentation on use

### ISSUE THREAD

**Issue by trezero** [essandess/macos-openvpn-server#1]
The shell script just displays everything. Did you intend to build an installer? or is there any documentation you can provide?

**Comment by essandess** [comment]
The shell script is a readme that provides detailed command line instructions and documentation. The process of building an OpenVPN server involves several steps, some fragile, that aren't handled well by an autoinstaller—setting up a pf firewall specific to your network, creating password protected TLS CA and certificates, emailing certs, uploading stuff in iTunes, and so forth. You're much better off reading the documentation in the shell script and understanding the setup as you'll be the one maintaining it and establishing its security.
