### ISSUE TITLE
openvpn server and client at the same time

### ISSUE THREAD

**Issue by copperlab** [essandess/macos-openvpn-server#4]
I am using your method and pf.conf for openvpn server and it has been working great.  I am in a position now.  Where I want to also have a VPN client on my mac mini and basically have some other devices on the network use that VPN connection as a gateway.  However, there is something in the pf.conf that is blocking the vpn client on the same machine. I can't figure it out.  All I know is if I revert to the stock pf.conf then the vpn client through tunnelblick works.  But when I load the one from your repo it stops working.  Thanks.

**Comment by essandess** [comment]
FWIW, I have VPN clients networked on the LAN with a version of the `pf.conf` In this repo.

I suggest stripping down `pf.conf` to a MWE, then uncomment the directives to send blocked packets to `pflog0` (iirc), and use `tcpdump` to see where the blockage might be.

If you see any issues with this repo’s `pf.conf`, please post them.

**Comment by copperlab** [comment]
There is nothing wrong with your pf.conf.  I used your repo as a start to a home project with a openvpn server so I can log into my network from the outside world.  And now want to add a vpn client to anonymize traffic.  I have unifi networking great and it is so slow for router hosted vpn.  So I want to offload to the vpn client.  You have a wonderful grasp of this stuff and I am drowning in it.  My email is available in my profile if you would be willing to have me pick your brain.  I am stuck...  But your repo works great... closing issue
