### ISSUE TITLE
Seems that I missed some steps or don't understand

### ISSUE THREAD

**Issue by saltarob** [essandess/macos-openvpn-server#5]
Hi,

I just tried to follow your instructions but very soon I got stuck.

`sudo rsync -va /Applications/Tunnelblick.app/Contents/Resources/easy-rsa-tunnelblick $OPENVPN_INSTALL`

From this I can assume that I have to install the Tunnelblick.app first.

> configure easy-rsa

`sudo install -m 755 -B .orig ./vars $OPENVPN_INSTALL`

It tells me No such file or directory.

What did I miss here?
Thank you for your help and sorry for my stupid questions.

**Comment by essandess** [comment]
The file `vars` is in this git repo, and that shell script assumes that you're in the directory you cloned the repo into.
