### ISSUE TITLE
please fix vars

### ISSUE THREAD

**Issue by andycarver101** [essandess/macos-openvpn-server#6]
https://ubuntuforums.org/showthread.php?t=2001055

**Comment by andycarver101** [comment]
the instruction make sense but seem out dated. 
I am running 10.14
The install causes ownership issues. I was wondering if the information regarding the vars file is complete as the scripts prompts to modify the vars but the wiki says to follow a generic config.

**Comment by essandess** [comment]
I don't believe that the instructions are outdated. I recommend handling the certificates under sudo for root file permissions and keeping the CA root locked down. 

I have a longer term plan to update to an `openssl.conf` approach for more automation, but won't get to that until my own personal CA expires in a bit.
